//   name  :  redux -actionsTypes  //
//   author : suman               //
//   Date  : 20/08/2021           //

/*  USERS  */
export const LOAD_USERS_START = "LOAD_USERS_START"
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS"
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR"

export const CREATE_USER_START = "CREATE_USER_START"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_ERROR = "CREATE_USER_ERROR"

export const DELETE_USER_START = "DELETE_USER_START"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"

export const UPDATE_USER_START = "UPDATE_USER_START"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

/* STUDENTS  */
export const LOAD_STUDENTS_START = "LOAD_STUDENTS_START";
export const LOAD_STUDENTS_SUCCESS = "LOAD_STUDENTS_SUCCESS";
export const LOAD_STUDENTS_ERROR = "LOAD_STUDENTS_ERROR";

export const CREATE_STUDENTS_START = "CREATE_STUDENTS_START";
export const CREATE_STUDENTS_SUCCESS = "CREATE_STUDENTS_SUCCESS";
export const CREATE_STUDENTS_ERROR = "CREATE_STUDENTS_ERROR";

export const DELETE_STUDENTS_START = "DELETE_STUDENTS_START";
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENTS_SUCCESS";
export const DELETE_STUDENTS_ERROR = "DELETE_STUDENTS_ERROR";

export const UPDATE_STUDENTS_START = "UPDATE_STUDENTS_START";
export const UPDATE_STUDENTS_SUCCESS = "UPDATE_STUDENTS_SUCCESS";
export const UPDATE_STUDENTS_ERROR = "UPDATE_STUDENTS_ERROR";



